name: Werbung-PMMP-PMMP
version: 1.1.1
api: 3.0.0
main: supercrafter333\werbung\werbung
author: supercrafter333

commands:
  werbung:
    description: §r§aMache Werbung-PMMP für deinen Shop!
    permission: werbung.cmd
    usage: "/werbung <text>"

permissions:
  werbung.cmd:
    default: true
