name: Announcements
version: 1.5.0
api: 3.0.0
main: tobypayneyt/announcements/announcements
author: tobypayneyt (original code by supercrafter333)
softdepend: EconomyAPI

commands:
  werbung:
    description: Announces the specified message!
    permission: werbung-pmmp.adversiting.cmd
    usage: "/announce <text>"
    aliases: ["announce"]

permissions:
  werbung-pmmp.advertising.bypass:
    default: op
    children:
      werbung-pmmp.adversiting.cmd:
        default: true
      werbung-pmmp.advertising.nopay:
        default: op