name: Werbung-PMMP
version: 1.0.0
api: [3.0.0, 4.0.0]
main: supercrafter333\w\werbung
author: supercrafter333

commands:
  werbung:
    description: §r§aMache Werbung für deinen Shop!
    permission: werbung.cmd
    usage: "/werbung <text>"

permissions:
  werbung.cmd:
    default: true
