name: Werbung-PMMP
version: 1.3.0
api: 3.0.0
main: supercrafter333\werbung\werbung
author: supercrafter333

commands:
  werbung:
    description: §r§aPromote your shop!
    permission: advertising.cmd
    usage: "/advertising <text>"
    aliases: ["advertising"]

permissions:
  advertising.cmd:
    default: true
