name: Werbung-PMMP
version: 1.5.0
api: 3.0.0
main: supercrafter333\werbung\werbung
author: supercrafter333

commands:
  werbung:
    description: §r§aPromote your shop!
    permission: werbung-pmmp.adversiting.cmd
    usage: "/advertising <text>"
    aliases: ["advertising"]

permissions:
  werbung-pmmp.advertising.bypass:
    default: op
    children:
      werbung-pmmp.adversiting.cmd:
        default: true
      werbung-pmmp.advertising.nopay:
        default: op